name: minecraft-daemon
base: core24 # the base snap is the execution environment for this snap
version: '0.0.1'
summary: Snap to run a minecraft server instance
description: |
  This snap starts a minecraft server instance
  the eula must manually be edited by,
  by going into the common directory for this snap,
  after the first launch.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

license: MIT

apps:
  minecraft-daemon:
    command: run-daemon
    daemon: simple
    plugs:
      - network
      - home
      - network-bind

parts:
  minecraft-daemon:
    plugin: nil

    build-packages:
      - openjdk-21-jre-headless
      - curl
      - sed
      - jq
      - nano
      - tar

    stage-packages:
      - openjdk-21-jre-headless
      - curl
      - sed
      - jq
      - nano
      - tar

  publish:
    plugin: dump
    source: scripts

